package mods.ffxisimplepacking.tools;

import net.minecraft.block.Block;
import net.minecraft.item.Item;

public class SpiItems
{
	public static void regListToAll()
	{
		SpiTools.addLisToSendBlockId(1, 0, 0, "Stone");
		SpiTools.addLisToSendBlockId(2, 0, 0, "Grass Block");
		SpiTools.addLisToSendBlockId(3, 0, 0, "Dirt");
		SpiTools.addLisToSendBlockId(4, 0, 0, "Cobblestone");
		SpiTools.addLisToSendBlockId(5, 0, 0, "Oak Wood Planks");
		SpiTools.addLisToSendBlockId(5, 1, 1, "Spruce Wood Planks");
		SpiTools.addLisToSendBlockId(5, 2, 2, "Birch Wood Planks");
		SpiTools.addLisToSendBlockId(5, 3, 3, "Jungle Wood Planks");
		SpiTools.addLisToSendBlockId(6, 0, 0, "Oak Sapling");
		SpiTools.addLisToSendBlockId(6, 1, 1, "Spruce Sapling");
		SpiTools.addLisToSendBlockId(6, 2, 2, "Birch Sapling");
		SpiTools.addLisToSendBlockId(6, 3, 3, "Jungle Sapling");
		SpiTools.addLisToSendBlockId(7, 0, 0, "Bedrock");
		SpiTools.addLisToSendBlockId(12, 0, 0, "Sand");
		SpiTools.addLisToSendBlockId(13, 0, 0, "Gravel");
		SpiTools.addLisToSendBlockId(14, 0, 0, "Gold Ore");
		SpiTools.addLisToSendBlockId(15, 0, 0, "Iron Ore");
		SpiTools.addLisToSendBlockId(16, 0, 0, "Coal Ore");
		SpiTools.addLisToSendBlockId(17, 0, 0, "Oak Wood");
		SpiTools.addLisToSendBlockId(17, 1, 1, "Spruce Wood");
		SpiTools.addLisToSendBlockId(17, 2, 2, "Birch Wood");
		SpiTools.addLisToSendBlockId(17, 3, 3, "Jungle Wood");
		SpiTools.addLisToSendBlockId(18, 0, 0, "Oak Leaves");
		SpiTools.addLisToSendBlockId(18, 1, 1, "Spruce Leaves");
		SpiTools.addLisToSendBlockId(18, 2, 2, "Birch Leaves");
		SpiTools.addLisToSendBlockId(18, 3, 3, "Jungle Leaves");
		SpiTools.addLisToSendBlockId(19, 0, 0, "Sponge");
		SpiTools.addLisToSendBlockId(20, 0, 0, "Glass");
		SpiTools.addLisToSendBlockId(21, 0, 0, "Lapis Lazuli Ore");
		SpiTools.addLisToSendBlockId(22, 0, 0, "Lapis Lazuli Block");
		SpiTools.addLisToSendBlockId(24, 0, 0, "Sandstone");
		SpiTools.addLisToSendBlockId(24, 1, 1, "Chiseled Sandstone");
		SpiTools.addLisToSendBlockId(24, 2, 2, "Smooth Sandstone");
		SpiTools.addLisToSendBlockId(30, 0, 0, "Cobweb");
		SpiTools.addLisToSendBlockId(31, 0, 0, "Shrub");
		SpiTools.addLisToSendBlockId(31, 1, 1, "Grass");
		SpiTools.addLisToSendBlockId(31, 2, 2, "Fern");
		SpiTools.addLisToSendBlockId(32, 0, 0, "Dead Bush");
		SpiTools.addLisToSendBlockId(35, 0, 0, "Wool");
		SpiTools.addLisToSendBlockId(35, 1, 1, "Orange Wool");
		SpiTools.addLisToSendBlockId(35, 2, 2, "Magenta Wool");
		SpiTools.addLisToSendBlockId(35, 3, 3, "Light Blue Wool");
		SpiTools.addLisToSendBlockId(35, 4, 4, "Yellow Wool");
		SpiTools.addLisToSendBlockId(35, 5, 5, "Lime Wool");
		SpiTools.addLisToSendBlockId(35, 6, 6, "Pink Wool");
		SpiTools.addLisToSendBlockId(35, 7, 7, "Gray Wool");
		SpiTools.addLisToSendBlockId(35, 8, 8, "Light Gray Wool");
		SpiTools.addLisToSendBlockId(35, 9, 9, "Cyan Wool");
		SpiTools.addLisToSendBlockId(35, 10, 10, "Purple Wool");
		SpiTools.addLisToSendBlockId(35, 11, 11, "Blue Wool");
		SpiTools.addLisToSendBlockId(35, 12, 12, "Brown Wool");
		SpiTools.addLisToSendBlockId(35, 13, 13, "Green Wool");
		SpiTools.addLisToSendBlockId(35, 14, 14, "Red Wool");
		SpiTools.addLisToSendBlockId(35, 15, 15, "Black Wool");
		SpiTools.addLisToSendBlockId(37, 0, 0, "Flower");
		SpiTools.addLisToSendBlockId(38, 0, 0, "Rose");
		SpiTools.addLisToSendBlockId(39, 0, 0, "Mushroom");
		SpiTools.addLisToSendBlockId(40, 0, 0, "Mushroom");
		SpiTools.addLisToSendBlockId(41, 0, 0, "Block of Gold");
		SpiTools.addLisToSendBlockId(42, 0, 0, "Block of Iron");
		SpiTools.addLisToSendBlockId(43, 0, 0, "Stone Slab");
		SpiTools.addLisToSendBlockId(43, 1, 1, "Sandstone Slab");
		SpiTools.addLisToSendBlockId(43, 2, 2, "Wooden Slab");
		SpiTools.addLisToSendBlockId(43, 3, 3, "Cobblestone Slab");
		SpiTools.addLisToSendBlockId(43, 4, 4, "Bricks Slab");
		SpiTools.addLisToSendBlockId(43, 5, 5, "Stone Bricks Slab");
		SpiTools.addLisToSendBlockId(43, 6, 6, "Nether Brick Slab");
		SpiTools.addLisToSendBlockId(43, 7, 7, "Quartz Slab");
		SpiTools.addLisToSendBlockId(44, 0, 0, "Stone Slab");
		SpiTools.addLisToSendBlockId(44, 1, 1, "Sandstone Slab");
		SpiTools.addLisToSendBlockId(44, 2, 2, "Wooden Slab");
		SpiTools.addLisToSendBlockId(44, 3, 3, "Cobblestone Slab");
		SpiTools.addLisToSendBlockId(44, 4, 4, "Bricks Slab");
		SpiTools.addLisToSendBlockId(44, 5, 5, "Stone Bricks Slab");
		SpiTools.addLisToSendBlockId(44, 6, 6, "Nether Brick Slab");
		SpiTools.addLisToSendBlockId(44, 7, 7, "Quartz Slab");
		SpiTools.addLisToSendBlockId(45, 0, 0, "Bricks");
		SpiTools.addLisToSendBlockId(47, 0, 0, "Bookshelf");
		SpiTools.addLisToSendBlockId(48, 0, 0, "Moss Stone");
		SpiTools.addLisToSendBlockId(49, 0, 0, "Obsidian");
		SpiTools.addLisToSendBlockId(50, 0, 0, "Torch");
		SpiTools.addLisToSendBlockId(53, 0, 0, "Oak Wood Stairs");
		SpiTools.addLisToSendBlockId(56, 0, 0, "Diamond Ore");
		SpiTools.addLisToSendBlockId(57, 0, 0, "Block of Diamond");
		SpiTools.addLisToSendBlockId(60, 0, 0, "Farmland");
		SpiTools.addLisToSendBlockId(67, 0, 0, "Stone Stairs");
		SpiTools.addLisToSendBlockId(69, 0, 0, "Lever");
		SpiTools.addLisToSendBlockId(70, 0, 0, "Pressure Plate");
		SpiTools.addLisToSendBlockId(72, 0, 0, "Pressure Plate");
		SpiTools.addLisToSendBlockId(73, 0, 0, "Redstone Ore");
		SpiTools.addLisToSendBlockId(74, 0, 0, "Redstone Ore");
		SpiTools.addLisToSendBlockId(77, 0, 0, "Button");
		SpiTools.addLisToSendBlockId(78, 0, 0, "Snow");
		SpiTools.addLisToSendBlockId(79, 0, 0, "Ice");
		SpiTools.addLisToSendBlockId(80, 0, 0, "Snow");
		SpiTools.addLisToSendBlockId(81, 0, 0, "Cactus");
		SpiTools.addLisToSendBlockId(82, 0, 0, "Clay");
		SpiTools.addLisToSendBlockId(85, 0, 0, "Fence");
		SpiTools.addLisToSendBlockId(86, 0, 0, "Pumpkin");
		SpiTools.addLisToSendBlockId(87, 0, 0, "Netherrack");
		SpiTools.addLisToSendBlockId(88, 0, 0, "Soul Sand");
		SpiTools.addLisToSendBlockId(89, 0, 0, "Glowstone");
		SpiTools.addLisToSendBlockId(91, 0, 0, "Jack o'Lantern");
		SpiTools.addLisToSendBlockId(96, 0, 0, "Trapdoor");
		SpiTools.addLisToSendBlockId(98, 0, 0, "Stone Bricks");
		SpiTools.addLisToSendBlockId(98, 1, 1, "Mossy Stone Bricks");
		SpiTools.addLisToSendBlockId(98, 2, 2, "Cracked Stone Bricks");
		SpiTools.addLisToSendBlockId(98, 3, 3, "Chiseled Stone Bricks");
		SpiTools.addLisToSendBlockId(101, 0, 0, "Iron Bars");
		SpiTools.addLisToSendBlockId(102, 0, 0, "Glass Pane");
		SpiTools.addLisToSendBlockId(103, 0, 0, "Melon");
		SpiTools.addLisToSendBlockId(106, 0, 0, "Vines");
		SpiTools.addLisToSendBlockId(107, 0, 0, "Fence Gate");
		SpiTools.addLisToSendBlockId(108, 0, 0, "Brick Stairs");
		SpiTools.addLisToSendBlockId(109, 0, 0, "Stone Brick Stairs");
		SpiTools.addLisToSendBlockId(110, 0, 0, "Mycelium");
		SpiTools.addLisToSendBlockId(111, 0, 0, "Lily Pad");
		SpiTools.addLisToSendBlockId(112, 0, 0, "Nether Brick");
		SpiTools.addLisToSendBlockId(113, 0, 0, "Nether Brick Fence");
		SpiTools.addLisToSendBlockId(114, 0, 0, "Nether Brick Stairs");
		SpiTools.addLisToSendBlockId(121, 0, 0, "End Stone");
		SpiTools.addLisToSendBlockId(125, 0, 0, "Oak Wood Slab");
		SpiTools.addLisToSendBlockId(125, 1, 1, "Spruce Wood Slab");
		SpiTools.addLisToSendBlockId(125, 2, 2, "Birch Wood Slab");
		SpiTools.addLisToSendBlockId(125, 3, 3, "Jungle Wood Slab");
		SpiTools.addLisToSendBlockId(126, 0, 0, "Oak Wood Slab");
		SpiTools.addLisToSendBlockId(126, 1, 1, "Spruce Wood Slab");
		SpiTools.addLisToSendBlockId(126, 2, 2, "Birch Wood Slab");
		SpiTools.addLisToSendBlockId(126, 3, 3, "Jungle Wood Slab");
		SpiTools.addLisToSendBlockId(128, 0, 0, "Sandstone Stairs");
		SpiTools.addLisToSendBlockId(129, 0, 0, "Emerald Ore");
		SpiTools.addLisToSendBlockId(133, 0, 0, "Block of Emerald");
		SpiTools.addLisToSendBlockId(134, 0, 0, "Spruce Wood Stairs");
		SpiTools.addLisToSendBlockId(135, 0, 0, "Birch Wood Stairs");
		SpiTools.addLisToSendBlockId(136, 0, 0, "Jungle Wood Stairs");
		SpiTools.addLisToSendBlockId(137, 0, 0, "Command Block");
		SpiTools.addLisToSendBlockId(139, 0, 0, "Cobblestone Wall");
		SpiTools.addLisToSendBlockId(139, 1, 1, "Mossy Cobblestone Wall");
		SpiTools.addLisToSendBlockId(143, 0, 0, "Button");
		SpiTools.addLisToSendBlockId(152, 0, 0, "Block of Redstone");
		SpiTools.addLisToSendBlockId(153, 0, 0, "Nether Quartz Ore");
		SpiTools.addLisToSendBlockId(155, 0, 0, "Block of Quartz");
		SpiTools.addLisToSendBlockId(155, 1, 1, "Chiseled Quartz Block");
		SpiTools.addLisToSendBlockId(155, 2, 2, "Pillar Quartz Block");
		SpiTools.addLisToSendBlockId(156, 0, 0, "Quartz Stairs");
		SpiTools.addLisToSendBlockId(159, 0, 0, "White Stained Clay");
		SpiTools.addLisToSendBlockId(159, 1, 1, "Orange Stained Clay");
		SpiTools.addLisToSendBlockId(159, 2, 2, "Magenta Stained Clay");
		SpiTools.addLisToSendBlockId(159, 3, 3, "Light Blue Stained Clay");
		SpiTools.addLisToSendBlockId(159, 4, 4, "Yellow Stained Clay");
		SpiTools.addLisToSendBlockId(159, 5, 5, "Lime Stained Clay");
		SpiTools.addLisToSendBlockId(159, 6, 6, "Pink Stained Clay");
		SpiTools.addLisToSendBlockId(159, 7, 7, "Gray Stained Clay");
		SpiTools.addLisToSendBlockId(159, 8, 8, "Light Gray Stained Clay");
		SpiTools.addLisToSendBlockId(159, 9, 9, "Cyan Stained Clay");
		SpiTools.addLisToSendBlockId(159, 10, 10, "Purple Stained Clay");
		SpiTools.addLisToSendBlockId(159, 11, 11, "Blue Stained Clay");
		SpiTools.addLisToSendBlockId(159, 12, 12, "Brown Stained Clay");
		SpiTools.addLisToSendBlockId(159, 13, 13, "Green Stained Clay");
		SpiTools.addLisToSendBlockId(159, 14, 14, "Red Stained Clay");
		SpiTools.addLisToSendBlockId(159, 15, 15, "Black Stained Clay");
		SpiTools.addLisToSendBlockId(170, 0, 0, "Hay Bale");
		SpiTools.addLisToSendBlockId(171, 0, 0, "Carpet");
		SpiTools.addLisToSendBlockId(171, 1, 1, "Orange Carpet");
		SpiTools.addLisToSendBlockId(171, 2, 2, "Magenta Carpet");
		SpiTools.addLisToSendBlockId(171, 3, 3, "Light Blue Carpet");
		SpiTools.addLisToSendBlockId(171, 4, 4, "Yellow Carpet");
		SpiTools.addLisToSendBlockId(171, 5, 5, "Lime Carpet");
		SpiTools.addLisToSendBlockId(171, 6, 6, "Pink Carpet");
		SpiTools.addLisToSendBlockId(171, 7, 7, "Gray Carpet");
		SpiTools.addLisToSendBlockId(171, 8, 8, "Light Gray Carpet");
		SpiTools.addLisToSendBlockId(171, 9, 9, "Cyan Carpet");
		SpiTools.addLisToSendBlockId(171, 10, 10, "Purple Carpet");
		SpiTools.addLisToSendBlockId(171, 11, 11, "Blue Carpet");
		SpiTools.addLisToSendBlockId(171, 12, 12, "Brown Carpet");
		SpiTools.addLisToSendBlockId(171, 13, 13, "Green Carpet");
		SpiTools.addLisToSendBlockId(171, 14, 14, "Red Carpet");
		SpiTools.addLisToSendBlockId(171, 15, 15, "Black Carpet");
		SpiTools.addLisToSendBlockId(172, 0, 0, "Hardened Clay");
		SpiTools.addLisToSendBlockId(173, 0, 0, "Block of Coal");

		SpiTools.addLisToSendItemId(4, 260, 0, 0, "Apple");
		SpiTools.addLisToSendItemId(7, 263, 0, 0, "Coal");
		SpiTools.addLisToSendItemId(7, 263, 1, 1, "Charcoal");
		SpiTools.addLisToSendItemId(8, 264, 0, 0, "Diamond");
		SpiTools.addLisToSendItemId(9, 265, 0, 0, "Iron Ingot");
		SpiTools.addLisToSendItemId(10, 266, 0, 0, "Gold Ingot");
		SpiTools.addLisToSendItemId(24, 280, 0, 0, "Stick");
		SpiTools.addLisToSendItemId(25, 281, 0, 0, "Bowl");
		SpiTools.addLisToSendItemId(26, 282, 0, 0, "Mushroom Stew");
		SpiTools.addLisToSendItemId(31, 287, 0, 0, "String");
		SpiTools.addLisToSendItemId(32, 288, 0, 0, "Feather");
		SpiTools.addLisToSendItemId(33, 289, 0, 0, "Gunpowder");
		SpiTools.addLisToSendItemId(39, 295, 0, 0, "Seeds");
		SpiTools.addLisToSendItemId(40, 296, 0, 0, "Wheat");
		SpiTools.addLisToSendItemId(41, 297, 0, 0, "Bread");
		SpiTools.addLisToSendItemId(62, 318, 0, 0, "Flint");
		SpiTools.addLisToSendItemId(63, 319, 0, 0, "Raw Porkchop");
		SpiTools.addLisToSendItemId(64, 320, 0, 0, "Cooked Porkchop");
		SpiTools.addLisToSendItemId(65, 321, 0, 0, "Painting");
		SpiTools.addLisToSendItemId(66, 322, 0, 0, "Golden Apple");
		SpiTools.addLisToSendItemId(67, 323, 0, 0, "Sign");
		SpiTools.addLisToSendItemId(68, 324, 0, 0, "Wooden Door");
		SpiTools.addLisToSendItemId(69, 325, 0, 0, "Bucket");
		SpiTools.addLisToSendItemId(70, 326, 0, 0, "Water Bucket");
		SpiTools.addLisToSendItemId(71, 327, 0, 0, "Lava Bucket");
		SpiTools.addLisToSendItemId(73, 329, 0, 0, "Saddle");
		SpiTools.addLisToSendItemId(74, 330, 0, 0, "Iron Door");
		SpiTools.addLisToSendItemId(75, 331, 0, 0, "Redstone");
		SpiTools.addLisToSendItemId(76, 332, 0, 0, "Snowball");
		SpiTools.addLisToSendItemId(78, 334, 0, 0, "Leather");
		SpiTools.addLisToSendItemId(79, 335, 0, 0, "Milk");
		SpiTools.addLisToSendItemId(80, 336, 0, 0, "Brick");
		SpiTools.addLisToSendItemId(81, 337, 0, 0, "Clay");
		SpiTools.addLisToSendItemId(82, 338, 0, 0, "Sugar Canes");
		SpiTools.addLisToSendItemId(83, 339, 0, 0, "Paper");
		SpiTools.addLisToSendItemId(84, 340, 0, 0, "Book");
		SpiTools.addLisToSendItemId(85, 341, 0, 0, "Slimeball");
		SpiTools.addLisToSendItemId(88, 344, 0, 0, "Egg");
		SpiTools.addLisToSendItemId(92, 348, 0, 0, "Glowstone Dust");
		SpiTools.addLisToSendItemId(93, 349, 0, 0, "Raw Fish");
		SpiTools.addLisToSendItemId(94, 350, 0, 0, "Cooked Fish");
		SpiTools.addLisToSendItemId(95, 351, 0, 0, "Ink Sac");
		SpiTools.addLisToSendItemId(95, 351, 1, 1, "Rose Red");
		SpiTools.addLisToSendItemId(95, 351, 2, 2, "Cactus Green");
		SpiTools.addLisToSendItemId(95, 351, 3, 3, "Cocoa Beans");
		SpiTools.addLisToSendItemId(95, 351, 4, 4, "Lapis Lazuli");
		SpiTools.addLisToSendItemId(95, 351, 5, 5, "Purple Dye");
		SpiTools.addLisToSendItemId(95, 351, 6, 6, "Cyan Dye");
		SpiTools.addLisToSendItemId(95, 351, 7, 7, "Light Gray Dye");
		SpiTools.addLisToSendItemId(95, 351, 8, 8, "Gray Dye");
		SpiTools.addLisToSendItemId(95, 351, 9, 9, "Pink Dye");
		SpiTools.addLisToSendItemId(95, 351, 10, 10, "Lime Dye");
		SpiTools.addLisToSendItemId(95, 351, 11, 11, "Dandelion Yellow");
		SpiTools.addLisToSendItemId(95, 351, 12, 12, "Light Blue Dye");
		SpiTools.addLisToSendItemId(95, 351, 13, 13, "Magenta Dye");
		SpiTools.addLisToSendItemId(95, 351, 14, 14, "Orange Dye");
		SpiTools.addLisToSendItemId(95, 351, 15, 15, "Bone Meal");
		SpiTools.addLisToSendItemId(96, 352, 0, 0, "Bone");
		SpiTools.addLisToSendItemId(97, 353, 0, 0, "Sugar");
		SpiTools.addLisToSendItemId(98, 354, 0, 0, "Cake");
		SpiTools.addLisToSendItemId(101, 357, 0, 0, "Cookie");
		SpiTools.addLisToSendItemId(104, 360, 0, 0, "Melon");
		SpiTools.addLisToSendItemId(105, 361, 0, 0, "Pumpkin Seeds");
		SpiTools.addLisToSendItemId(106, 362, 0, 0, "Melon Seeds");
		SpiTools.addLisToSendItemId(107, 363, 0, 0, "Raw Beef");
		SpiTools.addLisToSendItemId(108, 364, 0, 0, "Steak");
		SpiTools.addLisToSendItemId(109, 365, 0, 0, "Raw Chicken");
		SpiTools.addLisToSendItemId(110, 366, 0, 0, "Cooked Chicken");
		SpiTools.addLisToSendItemId(111, 367, 0, 0, "Rotten Flesh");
		SpiTools.addLisToSendItemId(112, 368, 0, 0, "Ender Pearl");
		SpiTools.addLisToSendItemId(113, 369, 0, 0, "Blaze Rod");
		SpiTools.addLisToSendItemId(114, 370, 0, 0, "Ghast Tear");
		SpiTools.addLisToSendItemId(115, 371, 0, 0, "Gold Nugget");
		SpiTools.addLisToSendItemId(116, 372, 0, 0, "Nether Wart");
		SpiTools.addLisToSendItemId(118, 374, 0, 0, "Glass Bottle");
		SpiTools.addLisToSendItemId(119, 375, 0, 0, "Spider Eye");
		SpiTools.addLisToSendItemId(120, 376, 0, 0, "Fermented Spider Eye");
		SpiTools.addLisToSendItemId(121, 377, 0, 0, "Blaze Powder");
		SpiTools.addLisToSendItemId(122, 378, 0, 0, "Magma Cream");
		SpiTools.addLisToSendItemId(125, 381, 0, 0, "Eye of Ender");
		SpiTools.addLisToSendItemId(126, 382, 0, 0, "Glistering Melon");
		SpiTools.addLisToSendItemId(129, 385, 0, 0, "Fire Charge");
		SpiTools.addLisToSendItemId(130, 386, 0, 0, "Book and Quill");
		SpiTools.addLisToSendItemId(132, 388, 0, 0, "Emerald");
		SpiTools.addLisToSendItemId(134, 390, 0, 0, "Flower Pot");
		SpiTools.addLisToSendItemId(135, 391, 0, 0, "Carrot");
		SpiTools.addLisToSendItemId(136, 392, 0, 0, "Potato");
		SpiTools.addLisToSendItemId(137, 393, 0, 0, "Baked Potato");
		SpiTools.addLisToSendItemId(138, 394, 0, 0, "Poisonous Potato");
		SpiTools.addLisToSendItemId(139, 395, 0, 0, "Empty Map");
		SpiTools.addLisToSendItemId(140, 396, 0, 0, "Golden Carrot");
		SpiTools.addLisToSendItemId(144, 400, 0, 0, "Pumpkin Pie");
		SpiTools.addLisToSendItemId(145, 401, 0, 0, "Firework Rocket");
		SpiTools.addLisToSendItemId(146, 402, 0, 0, "Firework Star");
		SpiTools.addLisToSendItemId(149, 405, 0, 0, "Nether Brick");
		SpiTools.addLisToSendItemId(150, 406, 0, 0, "Nether Quartz");
		SpiTools.addLisToSendItemId(164, 420, 0, 0, "Lead");
		SpiTools.addLisToSendItemId(165, 421, 0, 0, "Name Tag");
	}
}
